spring.application.name=Guarderia_Frontend

# 1. Puerto 8081 (para que no colisione con el backend que está en el 8080)
server.port=8081

# 2. Rutas para que Spring MVC encuentre los archivos .jsp
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# 3. URL de conexión hacia el Backend API REST
backend.api.url=http://localhost:8080/api
